export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

//Posts
export const SET_POSTS = "SET_POSTS";
export const SET_POST = "SET_POST";
export const SET_POST_COMMENTS = "SET_POST_COMMENTS";
export const SET_POST_LIKE = "SET_POST_LIKE";
export const ADDED_NEW_POST = "ADDED_NEW_POST";
export const ON_POST_DELETED = "ON_POST_DELETED";
export const ON_MY_POST_SET = "ON_MY_POST_SET";
export const ON_GET_MY_POSTS_COMMENTS = "ON_GET_MY_POSTS_COMMENTS";
export const REMOVE_POSTS_COMMENTS = "REMOVE_POSTS_COMMENTS";

//Chats 
export const ON_CHAT_GOT = "SET_USERS";
export const CHAT_DELETED = "CHAT_DELETED";
export const SET_READ_MESSAGE = "SET_READ_MESSAGE";
export const REMOVE_NOT_READ_MESSAGE = "REMOVE_NOT_READ_MESSAGE";
export const ON_PREVIOUS_MESSAGES = "ON_PREVIOUS_MESSAGES";

//Users
export const SET_USERS = "SET_USERS";
export const SET_USER = "SET_USER";
export const SET_CONTACT = "SET_CONTACT";
export const SET_FOLLOW = "SET_FOLLOW";
export const SET_FOLLOWS_ME = "SET_FOLLOWS_ME";
export const SET_REQUEST_CONTACT_INFO = "SET_REQUEST_CONTACT_INFO";
export const SET_INVITED_TO_STORE = "SET_INVITED_TO_STORE";
export const REMOVE_FOLLOWED = "REMOVE_FOLLOWED";
export const ON_REMOVED_REQUEST = "ON_REMOVED_REQUEST";
export const ON_REMOVED_FOLLOWER = "ON_REMOVED_FOLLOWER";
export const ON_ADD_FOLLOWED = "ON_ADD_FOLLOWED";
export const ON_GET_ACTIVITIES = "ON_GET_ACTIVITIES";
export const ON_GET_FOLLOWED_LIKES = "ON_GET_FOLLOWED_LIKES";
export const REMOVE_FOLLOWED_LIKE = "REMOVE_FOLLOWED_LIKE";

//UI
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const ACTIVITY_ON = "ACTIVITY_ON";